backend:
  name: git-gateway
  branch: master

media_folder: "img/portfolio"
public_folder: "img/portfolio"

collections:
  - name: "gallery"
    label: "Photo Gallery"
    files:
      - name: "photos"
        label: "Photos"
        file: "data/photos.json"
        fields:
          - label: "Photos"
            name: "photos"
            widget: "list"
            label_singular: "Photo"
            allow_add: true
            fields:
              - label: "Image"
                name: "src"
                widget: "image"
              - label: "Alt Text"
                name: "alt"
                widget: "string"
                hint: "Describe the photo for accessibility and SEO. E.g. Portrait photography of Hannah, second shot"
                required: true
